OSGP/Integration-Tests

fitnesse/FitNesseRoot/content.txt, fitnesse/update-deps.sh, osgp-platform-test/.settings/org.eclipse.core.resources.prefs, osgp-platform-test/pom.xml, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/adhocmanagement/GetStatusSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/adhocmanagement/ResumeScheduleSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/adhocmanagement/SetLightSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/adhocmanagement/SetRebootSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/adhocmanagement/SetTransitionSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/basicfunctions/ProtocolSequenceNumberSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/basicfunctions/VerifyAuthorizeDeviceFunctionSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/basicfunctions/VerifyAuthorizePlatformFunctionSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/config/PersistenceConfig.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/config/messaging/OsgpCoreMessagingConfig.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/configurationmanagement/GetConfigurationDataSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/configurationmanagement/SetConfigurationDataSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/deviceinstallation/RegisterDeviceSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/deviceinstallation/StartDeviceTestSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/deviceinstallation/StopDeviceTestSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/devicemanagement/ReceiveEventNotificationsSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/devicemanagement/RemoveDeviceSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/devicemanagement/SetEventNotificationsSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/devicemonitoring/GetActualPowerUsageSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/devicemonitoring/GetPowerUsageHistorySteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/firmwaremanagement/GetFirmwareVersionSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/firmwaremanagement/UpdateFirmwareSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/schedulemanagement/SetScheduleSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/schedulemanagement/SetTariffScheduleSteps.java, parent-integration-tests/pom.xml, pom.xml
=> Offloading

.gitmodules, fitnesse/FitNesseRoot/content.txt, osgp-platform-test/pom.xml, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/OslpTestUtils.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/adhocmanagement/GetStatusSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/adhocmanagement/ResumeScheduleSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/adhocmanagement/SetLightSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/adhocmanagement/SetRebootSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/config/OslpConfig.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/config/TestApplicationContext.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/config/messaging/MessagingConfig.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/config/messaging/ProtocolOslpMessagingConfig.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/configurationmanagement/GetConfigurationDataSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/configurationmanagement/SetConfigurationDataSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/deviceinstallation/StartDeviceTestSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/deviceinstallation/StopDeviceTestSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/devicemanagement/RevokeKeySteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/devicemanagement/SetEventNotificationsSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/devicemanagement/UpdateKeySteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/devicemonitoring/GetActualPowerUsageSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/devicemonitoring/GetPowerUsageHistorySteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/firmwaremanagement/GetFirmwareVersionSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/firmwaremanagement/UpdateFirmwareSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/schedulemanagement/SetScheduleSteps.java, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/schedulemanagement/SetTariffScheduleSteps.java, parent-integration-tests/pom.xml, pom.xml
=> Updates tests for signing-server changes. Connects to OSGP/Platform#163

fitnesse/FitNesseRoot/FlexOvl/WebUserManagement/AddUserForOrganisation/content.txt
Connects to SmartSocietyServices/Webapps#136
=> Security fixes.

fitnesse/FitNesseRoot/FlexOvl/WebApplicationOperator/HtmlEscaping/content.txt, fitnesse/FitNesseRoot/FlexOvl/WebApplicationOperator/HtmlEscaping/properties.xml, fitnesse/FitNesseRoot/RecentChanges/content.txt, fitnesse/FitNesseRoot/RecentChanges/properties.xml
Connects to SmartSocietyServices/Webapps#137
=> Adds acc. crit. for HTML escaping in web-operator app. Connects to SmartSocietyServices/Webapps#137

fitnesse/FitNesseRoot/content.txt, fitnesse/updateVersions.sh, osgp-platform-test/pom.xml, parent-integration-tests/pom.xml, pom.xml
Created updateVersions.sh to automatically update versions from POM files.
=> Feat enhance fitnesse content

.gitmodules, osgp-platform-test/src/test/java/com/alliander/osgp/acceptancetests/firmwaremanagement/GetFirmwareVersionSteps.java
=> FLEX-1357 ~ Adds FirmwareModuleType

fitnesse/FitNesseRoot/content.txt, osgp-platform-test/src/test/java/com/alliander/osgp/domain/core/entities/DeviceBuilder.java
Does not fix individual test cases, only makes sure the build does not
freeze
=> OP-331 - Fixes integration build

.gitmodules
- certralizes Hikari Connection Pool in Shared
- adds several settings (like idle timeout and minimum connections)
- splits database connection string into host, port and database name
=> OC-307 ~ Shared HikariCP.

cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/SmartMeteringConfiguration.feature
=> SLIM-882 Updates test, deletes the skip tag

.gitmodules, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/hooks/ScenarioHooks.java, cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/SmartMeteringConfiguration.feature
=> Feature slim 882 generate and replace keys

runTestsAtRemoteServer.sh
- Updated submodules
- Updated runscript
=> OC-374 ~ Updated run remote script

cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/SmartMeteringFirmware.feature
Removes skips for [@SmartMeteringFirmware] scenarios
=> SLIM-748 ~ Removes skips for @SmartMeteringFirmware scenarios

.gitmodules, cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/SmartMeteringInstallation.feature, cucumber-tests-platform/src/test/java/com/alliander/osgp/cucumber/platform/glue/steps/database/core/DeviceSteps.java
Implemented cucumber scenarios for coupling unbound devices.
=> Slim 976 couple unbound connected

.gitignore, .gitmodules, cucumber-tests-platform-microgrids/src/test/java/com/alliander/osgp/cucumber/platform/microgrids/PlatformMicrogridsDefaults.java, cucumber-tests-platform-microgrids/src/test/java/com/alliander/osgp/cucumber/platform/microgrids/PlatformMicrogridsKeys.java, cucumber-tests-platform-microgrids/src/test/java/com/alliander/osgp/cucumber/platform/microgrids/glue/steps/database/adapterprotocolie61850/Iec61850DeviceSteps.java, cucumber-tests-platform-microgrids/src/test/java/com/alliander/osgp/cucumber/platform/microgrids/glue/steps/reporting/ReportingSteps.java, cucumber-tests-platform-microgrids/src/test/java/com/alliander/osgp/cucumber/platform/microgrids/mocks/iec61850/Iec61850MockServer.java, cucumber-tests-platform-microgrids/src/test/resources/features/osgp-adapter-ws-microgrids/EnableReporting.feature
=> Zs 232 enable reporting

cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/support/ws/smartmetering/configuration/SetAlarmNotificationsRequestFactory.java, cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/SmartMeteringConfiguration.feature
=> Feature-SLIM-1115-set alarm notifications with all alarm notifications

.gitmodules, cucumber-tests-platform-microgrids/src/test/resources/features/osgp-adapter-ws-microgrids/GetDataAlternativeScenarios.feature
=> ZS-274 When fcmodelnode is null exception occurs

.gitmodules, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringbundle/BundledFindEventsSteps.java, cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/bundle/BundledFindEvents.feature
=> SLIM-1225 Fix find events response when no events are found

cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmanagement/AbstractFindEventsReads.java, cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/SmartMeteringManagement.feature
SLIM-1225 
Test this [@SmartMetering]
=> SLIM-1225 Adjustments for CC test for find events

.gitmodules, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringbundle/BundledFindEventsSteps.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmanagement/AbstractFindEventsReads.java, cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/SmartMeteringManagement.feature, cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/bundle/BundledFindEvents.feature
=> SLIM-1443 Revert slim 1225

.gitmodules, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/database/device/DlmsDeviceSteps.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringconfiguration/SetEncryptionKeyExchangeOnGMeter.java, cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/SmartMeteringConfiguration.feature
SLIM-1387, test [@SmartMeteringConfiguration]
=> Slim 1387 Successful exchange encryption key on new m bus device

cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/AcceptanceTests.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/functional/exceptions/FunctionalExceptionsSteps.java, cucumber-tests-platform-smartmetering/src/test/resources/features/functional-exceptions/FunctionalExceptionsOrganisations.feature, cucumber-tests-platform/src/test/java/com/alliander/osgp/cucumber/platform/PlatformKeys.java
The organisation LianderNetManagement was chosen in the scenario, because
there is a certificate of that organisation in the ../certificates
folder.
=> SLIM-1123: Created a test for the UNKNOWN_ORGANISATION exception. 

.gitmodules, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmanagement/SetDeviceCommunicationSettings.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmanagement/SetDeviceCommunicationSettingsSteps.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/support/ws/smartmetering/management/SetDeviceCommunicationSettingsRequestDataFactory.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/support/ws/smartmetering/management/SetDeviceCommunicationSettingsRequestFactory.java, cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/SmartMeteringManagement.feature
SLIM-473 with tests [@SmartMetering]
=> Feature slim 473 manage configuration of device communication settings

.gitmodules, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmonitoring/ActualMeterReadsGasSteps.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmonitoring/ActualMeterReadsSteps.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmonitoring/ClearAlarmRegisterSteps.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmonitoring/PeriodicMeterReadsGasSteps.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmonitoring/PeriodicMeterReadsSteps.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmonitoring/ProfileGenericDataSteps.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmonitoring/ReadAlarmRegisterSteps.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/support/ws/smartmetering/monitoring/ClearAlarmRegisterRequestFactory.java, cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/SmartMeteringMonitoring.feature
SLIM-1421 and tests [SmartMetering]
=> SLIM-1421 Adds ClearAlarmRegister operation to cucumber

cucumber-tests-platform-common/src/test/java/com/alliander/osgp/cucumber/platform/common/AcceptanceTests.java, cucumber-tests-platform-microgrids/src/test/java/com/alliander/osgp/cucumber/platform/microgrids/AcceptanceTests.java, cucumber-tests-platform-microgrids/src/test/resources/features/osgp-adapter-ws-microgrids/ConnectionReestablish.feature, cucumber-tests-platform-publiclighting/src/test/java/com/alliander/osgp/cucumber/platform/publiclighting/AcceptanceTests.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/AcceptanceTests.java, jenkins/pipeline/OSGP Integration-Tests pr.groovy
not carried out in the pr build stage.
=> OC-355: Introduces NightlyBuildOnly tag, scenario's with that tag are

cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/builders/entities/BaseDeviceBuilder.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/glue/steps/functional/exceptions/FunctionalExceptionsSteps.java, cucumber-tests-platform-smartmetering/src/test/java/com/alliander/osgp/cucumber/platform/smartmetering/support/ws/smartmetering/SmartMeteringBaseClient.java, cucumber-tests-platform-smartmetering/src/test/resources/features/functional-exceptions/FunctionalExceptionsConnections.feature
Introduced FunctionalExceptions scenarios for connection errors.
=> Slim 1127 cucumber tests functional exceptions connections

cucumber-tests-platform-microgrids/src/test/java/com/alliander/osgp/cucumber/platform/microgrids/glue/steps/reporting/ReportingSteps.java, cucumber-tests-platform-microgrids/src/test/java/com/alliander/osgp/cucumber/platform/microgrids/mocks/iec61850/Iec61850MockServer.java
=> Adds retrying for starting the simulator as part of a restart

.gitmodules
Feature branch is only set up so that the right components will be deployed in the PR test environment.
Pull request can be closed when done, deleting the branch; don't merge into development.
=> SLIM-1662 Configures Shared submodule branch for tests

.gitmodules, cucumber-tests-platform-microgrids/pom.xml, parent-integration-tests/pom.xml
=> Build fix for iec61850 simulator war

cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/housekeeping/ResponseDataCleanupJob.feature
=> Fixes response data cleanup test

.gitmodules, cucumber-tests-platform-common/src/test/java/org/opensmartgridplatform/cucumber/platform/common/glue/steps/database/ws/NotificationWebServiceConfigurationBuilder.java, cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/database/DlmsDatabase.java
=> OC-380 Removes circuit breaker config for smart metering notification
